global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  # 抓取您的 Spring Boot 应用的指标
  - job_name: 'backend'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s # 抓取频率
    static_configs:
      - targets: ['backend:8080']
  # 抓取 Prometheus 自身的指标
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]